### ISSUE TITLE
Confirm axes ranges make sense to opsz-max

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex#261]
In the past we discussed the inherent limitations of using OS/2 weight/width class values for optical size families; the width axis is the worst for this, because "% of default" doesn't make any sense at all when that value itself varies through the design space, as it typically does for optical size variations, and even weight variations.... So we have to pick one "width default" style and only vary the width axis to deduce the % from that default to use for the Width axis values for the whole design space. I argued in the past, and @dberlow accepted, that the opsz-max default vars should be used against the opsz-max-wdth-[min,max] duovars to determine this. 

But reviewing the Flex TTF posted 6 days ago, I note that the weight axis is ranged 100..1,000, not 10..1,000 or something that is relevant to the opsz-max. 

Therefore I think we ought to either adjust the range of wght, or wdth, so that they are consistent in their solution to the vexing OS/2 values problem.

**Comment by dberlow** [comment]
Not all the os/2 values are of equal vexation. The situation with width was that it’s hopeless to use for justification or anything by sliding and gross fitting to line regardless of weight or spacing match. So, if we’re using xtra for that, I don’t care what width values there are, though I preferred keeping them at the default, 14 pt values for all.

I don’t know if changing the weight values for the whole space, to reflect the situation at 144, is a good idea, but it sounds a lot like trying to turn it into a parameter, which it isn’t.

On Feb 28, 2022, at 4:50 PM, Dave Crossland ***@***.***> wrote:

﻿
In the past we discussed the inherent limitations of using OS/2 weight/width class values for optical size families; the width axis is the worst for this, because "% of default" doesn't make any sense at all when that value itself varies through the design space, as it typically does for optical size variations, and even weight variations.... So we have to pick one "width default" style and only vary the width axis to deduce the % from that default to use for the Width axis values for the whole design space. I argued in the past, and @dberlow accepted, that the opsz-max default vars should be used against the opsz-max-wdth-[min,max] duovars to determine this.

But reviewing the Flex TTF posted 6 days ago, I note that the weight axis is ranged 100..1,000, not 10..1,000 or something that is relevant to the opsz-max.

Therefore I think we ought to either adjust the range of wght, or wdth, so that they are consistent in their solution to the vexing OS/2 values problem.

**Comment by davelab6** [comment]
So your recommendation is to range weight and width at the 14pt, not 144pt? They can only be ranged for one size.

**Comment by dberlow** [comment]
Yes. Users need to have a “normal” range to deal with, I think. If understand, you want to change the wght Min at 14pt to wght10. If we do, all the weights from 10 to 400 are now changed? Or only the weights from 100 down to 10, using avar? I ask because now one have used 100 much, so making it 10 would not hurt, but the do,use, e.g. 300, which I think we need to keep the same/similar.

…then I have to look and see if we still have consistent luminance in each weight over the size range? Otherwise all that I’ve evangelized about simple ramps is dead, below 400,  I think…

**Comment by davelab6** [comment]
Consistent luminance in each weight over the size range is certainly important, so indeed I expect recalibrating the wght range min from 100 to 10 should be about the '200 to min' (or 150 to min, etc) segment, which would be 'stretched' with avar, such that instead of 100 units there are 190 units - which affords graphic designers nearly 2x more finer control over weight selection in the larger optical sizes.

**Comment by dberlow** [comment]
It already is 100-1000. And the thing people asked for below 100 is, so
far, for animation.

 "...affords graphic designers nearly 2x more finer control over weight
selection in the larger optical sizes."

;) it does? the control being over the amount of parametric change there
is, not the OS/2 numeric space, the numeric space is an illusionary mask.
There are 160of the real values from wght400 to wght10, and 600 or so from
wght400 to wght1000. The means, above 400 there is  1:1 relationship
between OS/2 and the 2048 em we have. Below 400, there are many more OS/2
values than actual units under control, like 3:1 or so.

https://docs.google.com/spreadsheets/d/1FqdS286t0cxxZxtk7fP1qDh90ChrEOcoNo5R8IqSar0/edit#gid=2126116650

if you want look at the real numbers. XOPQ goes down to 3< GS Flex goes
down to 2... It's up to you and if anything goes wrong with either or any
choice, I promise to help fix it promptly.

**Comment by davelab6** [comment]
> the numeric space is an illusionary mask

Maybe indeed I should just give up trying to rationalize OS/2 values, they are deeply irrational and I just have to accept that. Let's discuss in a call later today.

**Comment by dberlow** [comment]
pleasseee, I'm begging you not in front of the children.

;)

**Comment by davelab6** [comment]
I gave up :)
