### ISSUE TITLE
Some symbols weight isn't dialed back to fit in like the others - 14 opsz | 1000 wght

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/roboto-flex#297]
When it occurs, this problem of excessive weight matching with letters looks particularly mushy in: § + ≠ ≠ ≥ etc. 

Note that it isn't inevitable as it contrasts quite a lot with the treatment of ¶ † * %

14
<img width="904" alt="image" src="https://user-images.githubusercontent.com/2181213/157123846-d29cc205-7fb9-491d-952e-77c3f981203b.png">

8 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/2181213/157124035-fea37403-4c7b-4f8f-9d26-e162d078a8da.png">
Zoomed in 8
<img width="949" alt="image" src="https://user-images.githubusercontent.com/2181213/157124110-ef3d9ed9-b6f7-4347-a358-4f795c893af4.png">

144
<img width="484" alt="image" src="https://user-images.githubusercontent.com/2181213/157124451-187dd743-b057-46a4-bd77-9357cce334c4.png">

**Comment by dberlow** [comment]
In some cases, are you sure you are not mixing fallback glyphs from a default family with two weights, with a stylistically separate style from a variable font, and expecting dialing back to those to work?

There are glyphs, like the plus minus-sign, and > than or = to, that were never intended to weight up to 1000 at 14 or smaller, but, cannot appear of a different weight than - (minus), and run out of vertical and horizontal freedom to do so.  if we lighter those to a whole new sub-weight, we'd have to add intermediates to stop that as the the weight lightens and size increases, or create contrast in those glyphs up to 14 and across all the weights and widths. 

At larger sizes we have more freedom to overlap to tiny counters, and some lightening.

**Comment by davelab6** [comment]
@EbenSorkin since your proofing tool doesn't correctly handle font fallback (eg it is showing glyphs that aren't in the tested font with no indication that they are from another font, which can be handled with better proof input text processing (removing all the characters in in the proof document that are not in the tested font's cmap) or better proof rendering (such as using Adobe NotDef or Adobe Blank fonts)) and @dberlow provides a convincing explanation of how he has handled some glyphs in extreme weights, I'll close this.
