### ISSUE TITLE
Variable axis naming not matching Google fonts

### ISSUE THREAD

**Issue by mjsxi** [googlefonts/roboto-flex#355]
I was wondering if we could have the naming of the font variations better match how they are on Google fonts? Maybe even match the order they're presented on there so its easier to work with? Was playing around with it in Figma and the naming doesn't make much sense but maybe I'm missing something?

How the variables appear on Google fonts:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/3400341/168333392-0622353e-f95a-42b1-833b-67664a7fd126.png">

How the variables appear on Figma:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/3400341/168333861-fb1adeea-1609-4c77-9c6e-e1d890880cb0.png">

**Comment by davelab6** [comment]
@mjsxi we already addressed this using the font in this repo, but it will take time for the next release to percolate down to Figma, as it appears they self-host the fonts, and don't take them from here or Google Fonts via any API.

You can see the new labels going into the fonts here:

https://github.com/googlefonts/roboto-flex/pull/340/files

In the GF catalog Type Tester and Sidebar, we elide "Parametric" form the axis names since they are space constrained; in the GF Knowledge Glossary we use the full names.

**Comment by mjsxi** [comment]
@davelab6 thanks for getting back to me and appreciate the explainer! Happy its coming!!
